// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpzzoppgzfobkaljkstr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwenpvcHBnemZvYmthbGprc3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTYwODQsImV4cCI6MjA3Mjc3MjA4NH0.-VWdDkOhiS7p2Ql-b9z6X-tqVQiBMfQ1H1HsgpnNy6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});